import React from 'react';
import './index.css';
import Question from './question.js';
import Answer from './answer.js';

export default function ArticleWatching() {
  return (
    <>
    <div className="huge">
    Watching the mind
    </div>
    <div className="body">
    <Question>
     I practised breath watching meditation for 21 days.
     When I sit for meditation, sometimes its very joyous, sometimes the
     mind doesnt become still.
     My mind thinks so many thoughts, it is amazing sometimes, the amount
     of thoughts.
     </Question>
    <Answer>
    Its still your mind's trick. Please, look deeper and deeper with
    awareness. Just look how you think "this meditation was joyous", "some times not"
    ...how do you know this?? by using your mind right?
    What ever you experience it is also your mind's manipulation.

    Thoughts are the feed for your mind. With out your presence, generation
    of thoughts is not possible for the Mind. So Mind always need you and your
    presence for its LIFE. With out you it can't survive.

    So it initially throw some pleasant situations then some times unpleasant
    situations so that you start think about those moments. If you are still
    not ready to look all his trick, it will start throwing colors and light
    then star etc., its like a trap which is generated by your mind.

    Only awareness will help you to solve this you just need to keep your self
    from all those things and just watch the happening in your body and mind
    as a simple observer. Just watch, don't respond to any situations.
    Don't try to stop, neither support, just watch it.
    </Answer>

    <Question>When I sit for dhyanam, i sit with head, spine
    straight. but after sometime my head droops to the right. Should I
    correct it or let it be ?
    </Question>
    <Answer>
    Its because of our body metabolic rate will reduce upto 40 to 60 % when
    ever we enter into some still state. Due to this our body and neck become so relaxed.
    Just leave that, don't try to correct. Just enjoy your precence
    </Answer>
    </div>
    </>
  );
}
